#include "UpdateChecker.h"

#include <cctype>

#include "Platform/IPlatform.h"

// Baked-in build identity (generated by CMake from git at build time). The fallback keeps
// the file self-contained for tooling/IDEs that build without the generated header.
#if __has_include("BuildInfo.h")
#include "BuildInfo.h"
#else
namespace sfe
{
constexpr const char* kBuildCommit = "unknown";
constexpr const char* kBuildCommitShort = "unknown";
constexpr const char* kBuildRepo = "NoahSteam/RomHackingTools";
}
#endif

namespace sfe
{

namespace
{
std::string LowerHex(const std::string& s)
{
    std::string out = s;
    for (char& c : out) c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    return out;
}

// The commit whose newness we compare against, minus a "-dirty" working-tree marker.
std::string LocalCommitClean()
{
    std::string c = kBuildCommit;
    const std::string::size_type dash = c.find("-dirty");
    if (dash != std::string::npos) c.erase(dash);
    return LowerHex(c);
}
}  // namespace

std::string ExtractLatestCommitSha(const std::string& json)
{
    // GitHub's /commits/<ref> reply opens with {"sha":"<40 hex>",... — grab the first
    // "sha" string value. Deliberately dependency-free (no JSON lib) since we need exactly
    // one well-known field.
    std::string::size_type key = json.find("\"sha\"");
    if (key == std::string::npos) return "";
    std::string::size_type colon = json.find(':', key + 5);
    if (colon == std::string::npos) return "";
    std::string::size_type open = json.find('"', colon + 1);
    if (open == std::string::npos) return "";
    std::string::size_type close = json.find('"', open + 1);
    if (close == std::string::npos) return "";
    std::string sha = json.substr(open + 1, close - open - 1);
    // Sanity: a commit SHA is 40 hex chars.
    if (sha.size() < 7) return "";
    for (char c : sha)
        if (!std::isxdigit(static_cast<unsigned char>(c))) return "";
    return sha;
}

const char* UpdateChecker::BuildCommit() { return kBuildCommit; }
const char* UpdateChecker::BuildCommitShort() { return kBuildCommitShort; }

UpdateChecker::~UpdateChecker()
{
    if (mThread.joinable()) mThread.join();
}

void UpdateChecker::Start(IPlatform& platform)
{
    {
        std::lock_guard<std::mutex> lock(mMutex);
        if (mState == State::Checking) return;   // one in flight already
        mState = State::Checking;
        mMessage = "Checking GitHub for a newer build\xe2\x80\xa6";
        mLatestShort.clear();
    }
    if (mThread.joinable()) mThread.join();   // reap the previous run
    mThread = std::thread(&UpdateChecker::Run, this, &platform);
}

UpdateChecker::State UpdateChecker::GetState() const
{
    std::lock_guard<std::mutex> lock(mMutex);
    return mState;
}

std::string UpdateChecker::Message() const
{
    std::lock_guard<std::mutex> lock(mMutex);
    return mMessage;
}

std::string UpdateChecker::LatestShort() const
{
    std::lock_guard<std::mutex> lock(mMutex);
    return mLatestShort;
}

void UpdateChecker::Run(UpdateChecker* self, IPlatform* platform)
{
    auto finish = [self](State s, std::string msg, std::string latestShort = {}) {
        std::lock_guard<std::mutex> lock(self->mMutex);
        self->mState = s;
        self->mMessage = std::move(msg);
        self->mLatestShort = std::move(latestShort);
    };

    const std::string local = LocalCommitClean();
    if (local.empty() || local == "unknown")
    {
        finish(State::Error,
               "This is a development build (no recorded commit), so it can't be compared "
               "against GitHub.");
        return;
    }

    const std::string url =
        std::string("https://api.github.com/repos/") + kBuildRepo + "/commits/HEAD";

    IPlatform::HttpResponse resp;
    const bool ok = platform->HttpsGet(url, "SaturnExplorer-UpdateCheck", resp);
    if (!ok)
    {
        // Distinguish "this build can't do HTTPS" from a real network failure so the UI
        // can word it correctly.
        const bool unsupported = resp.error.find("not available") != std::string::npos;
        finish(unsupported ? State::Unsupported : State::Error,
               resp.error.empty() ? "Could not reach GitHub." : resp.error);
        return;
    }
    if (resp.status != 200)
    {
        finish(State::Error,
               "GitHub returned HTTP " + std::to_string(resp.status) +
                   " (rate-limited, or the repo/branch moved).");
        return;
    }

    const std::string remote = LowerHex(ExtractLatestCommitSha(resp.body));
    if (remote.empty())
    {
        finish(State::Error, "Couldn't read the latest commit from GitHub's reply.");
        return;
    }
    const std::string remoteShort = remote.substr(0, 10);

    if (remote == local)
    {
        finish(State::UpToDate,
               std::string("You're on the latest build (") + kBuildCommitShort + ").",
               remoteShort);
    }
    else
    {
        finish(State::UpdateAvailable,
               std::string("A different build is on GitHub. You have ") + kBuildCommitShort +
                   ", latest is " + remoteShort +
                   ". Pull the repo and rebuild (or grab the new binary) to update.",
               remoteShort);
    }
}

}  // namespace sfe
