// UpdateChecker — "is there a newer build on GitHub?" Portable across platforms: it
// talks only to IPlatform::HttpsGet (Seam C), so Windows (WinHTTP), a future macOS build
// (libcurl), and the browser (unsupported) all share this one orchestration. The build's
// own commit is baked in at compile time (BuildInfo.h, generated by CMake from git); the
// check fetches the latest commit on the repo's default branch and compares.
//
// The HTTPS GET blocks, so it runs on a worker thread; the UI polls State()/Message()
// each frame. No ImGui, no platform code here.
#pragma once

#include <atomic>
#include <mutex>
#include <string>
#include <thread>

namespace sfe
{

class IPlatform;

class UpdateChecker
{
public:
    enum class State
    {
        Idle,             // never run this session
        Checking,         // request in flight on the worker thread
        UpToDate,         // local build == latest on the default branch
        UpdateAvailable,  // they differ (a newer — or just different — build exists)
        Unsupported,      // this platform build has no HTTPS (e.g. the browser)
        Error             // transport / parse failure, or an unknown local build
    };

    ~UpdateChecker();

    // Kick off a check (no-op while one is already running). Runs HttpsGet on a worker
    // thread against 'platform'; poll State() afterwards. 'platform' must outlive the check.
    void Start(IPlatform& platform);

    State       GetState() const;
    std::string Message() const;      // human-readable status detail
    std::string LatestShort() const;  // short SHA of the latest remote commit, when known
    bool        Busy() const { return GetState() == State::Checking; }

    // The build's own commit (baked in at compile time); "unknown" for a dev build.
    static const char* BuildCommit();
    static const char* BuildCommitShort();

private:
    static void Run(UpdateChecker* self, IPlatform* platform);

    mutable std::mutex mMutex;
    State              mState = State::Idle;
    std::string        mMessage;
    std::string        mLatestShort;
    std::thread        mThread;
};

// Extract the top-level commit "sha" from GitHub's /commits/<ref> JSON. Returns the 40-char
// hex string, or "" if not found. Free function so it is trivially unit-testable.
std::string ExtractLatestCommitSha(const std::string& json);

}  // namespace sfe
