# Write FrontEnd/src/Decompiler/Sh2SpecData.h: the four files the decompiler opens at runtime
# for SuperH:BE:32:SH-2, embedded as byte arrays so the app ships them inside its executable
# (SpecBundle materialises them into the config dir; PLAN.md A5). Run by the se-regen-sla
# target after se-sleighc has rewritten sh-2.sla. Inputs (passed with -D):
#   SPEC_DIR : FrontEnd/third_party/ghidra-decompiler/processors/SuperH
#   OUT_FILE : destination header
#
# The bytes are stored uncompressed, unlike the fonts (binary_to_compressed_c's stb_compress +
# base85). That keeps the decoder out of SpecBundle -- ImGui's is private to imgui_draw.cpp --
# and lets SlaFreshnessTests compare the embedded copy with the files on disk directly. The
# .sla is zlib-compressed already and the XML files are a few KiB, so nothing is lost.

set(files superh.ldefs superh.pspec superh.cspec sh-2.sla)

set(body "")
set(table "")
set(index 0)
foreach(name ${files})
    set(path "${SPEC_DIR}/${name}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "GenerateSpecData: missing ${path}")
    endif()
    file(SIZE "${path}" size)
    file(READ "${path}" hex HEX)
    # Two hex digits per byte -> "0xNN," with a line break every 16 bytes.
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n    " bytes "${bytes}")
    string(APPEND body "// ${name} (${size} bytes)\n")
    string(APPEND body "static const unsigned char kSh2SpecFile${index}[${size}] = {\n    ${bytes}\n};\n\n")
    string(APPEND table "    { \"${name}\", kSh2SpecFile${index}, ${size}u },\n")
    math(EXPR index "${index} + 1")
endforeach()

file(WRITE "${OUT_FILE}.tmp"
"// Generated by cmake/GenerateSpecData.cmake (build target se-regen-sla) -- do not edit.
// The SuperH:BE:32:SH-2 language files from FrontEnd/third_party/ghidra-decompiler/
// processors/SuperH, embedded byte for byte. SlaFreshnessTests fails if they drift from the
// vendored files or from what se-sleighc compiles the .slaspec into.
#pragma once

#include <cstddef>

namespace sfe
{
namespace decomp
{

struct EmbeddedSpecFile
{
    const char* name;
    const unsigned char* data;
    unsigned int size;
};

${body}static const EmbeddedSpecFile kSh2SpecFiles[] = {
${table}};

static const size_t kSh2SpecFileCount = sizeof(kSh2SpecFiles) / sizeof(kSh2SpecFiles[0]);

}  // namespace decomp
}  // namespace sfe
")
# Only replace the header when it changed, so an unchanged regeneration does not rebuild
# everything that includes it.
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${OUT_FILE}.tmp" "${OUT_FILE}")
file(REMOVE "${OUT_FILE}.tmp")
